<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

declare(strict_types=1);

namespace core_reportbuilder\local\report;

/**
 * Encapsulates the SELECT and GROUP BY fragments derived from a set of report columns
 *
 * Multiple report columns frequently reference the same underlying database expression (e.g. several
 * "user fullname" columns built from the same first/last-name fields). Without deduplication the report
 * SELECT clause emits the same expression many times, which is wasteful and bloats result-set size.
 *
 * This module owns the field deduplication concern end-to-end:
 *
 * - {@see get_select_fields} returns the deduplicated SELECT fragments, with each duplicate alias
 *   recorded internally so it can be re-applied where needed.
 * - {@see get_groupby_fields} returns the per-column GROUP BY fragments, already rewritten so they
 *   reference the canonical aliases that actually appear in the SELECT.
 * - {@see rewrite} rewrites a free-form fragment (typically an ORDER BY field) the same way.
 * - {@see rehydrate} copies values from canonical aliases back into the rewritten aliases on a
 *   fetched row, so column formatters continue to read their own per-column aliases unchanged.
 *
 * Eligibility for deduplication is conservative:
 *
 * - Field SQL must be textually identical *after* per-column parameter renaming has been applied
 *   (which {@see column::get_fields} performs). Parameterised fields naturally diverge once
 *   parameter names are prefixed with the column index, so they fall through.
 * - The owning column must not be aggregated. Aggregation wraps the field SQL, producing distinct
 *   text that cannot collide with raw fields.
 *
 * @package     core_reportbuilder
 * @copyright   2026 Paul Holden <paulh@moodle.com>
 * @license     http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
final class report_select {

    /**
     * Pattern matching a "{sql} AS {alias}" field expression where alias has the canonical
     * "c{index}_{name}" form generated by {@see column::get_fields}
     */
    private const FIELD_PATTERN = '/^(?<sql>.*) AS (?<alias>c\d+_\w+)$/s';

    /**
     * Pattern matching a single canonical column alias as a whole word
     */
    private const ALIAS_PATTERN = '/\bc\d+_\w+\b/';

    /**
     * @param string[] $selectfields Ordered SELECT fragments, with duplicates collapsed
     * @param string[] $groupbyfields Ordered GROUP BY fragments, with duplicate aliases rewritten
     * @param array<string, string> $aliasmap Map from collapsed alias to canonical alias
     */
    private function __construct(
        private readonly array $selectfields,
        private readonly array $groupbyfields,
        private readonly array $aliasmap,
    ) {
    }

    /**
     * Build a report_select describing the SELECT/GROUP BY shape for the given columns.
     *
     * @param column[] $columns Active report columns, in the order they appear in the report.
     * @param bool $forcegroupby Force every column's GROUP BY fragments to be included regardless of
     *      whether any column is aggregated. Reports configured to deduplicate rows ("unique rows")
     *      need this; otherwise GROUP BY fragments are only included when aggregation is in effect.
     */
    public static function for_columns(array $columns, bool $forcegroupby = false): self {
        $hasaggregated = false;
        foreach ($columns as $column) {
            if ($column->get_aggregation() !== null) {
                $hasaggregated = true;
                break;
            }
        }

        $selectfields = [];
        $sqltoalias = [];
        $aliasmap = [];
        $groupbyfields = [];

        foreach ($columns as $column) {
            $columnaggregation = $column->get_aggregation();
            $aggregated = $columnaggregation !== null;

            foreach ($column->get_fields() as $field) {
                if ($aggregated || !preg_match(self::FIELD_PATTERN, $field, $matches)) {
                    // Aggregated columns (and any non-canonical fragments) are emitted verbatim and
                    // are never collapsed against raw-field columns.
                    $selectfields[] = $field;
                    continue;
                }

                $sql = $matches['sql'];
                $alias = $matches['alias'];

                if (array_key_exists($sql, $sqltoalias)) {
                    // Same expression already emitted - record an alias rewrite, but don't add the
                    // field a second time.
                    $aliasmap[$alias] = $sqltoalias[$sql];
                } else {
                    $sqltoalias[$sql] = $alias;
                    $selectfields[] = $field;
                }
            }

            // Per-column GROUP BY: include a column's group-by fragments when group-by is forced, or
            // when at least one column is aggregated and this column should contribute to GROUP BY.
            if ($forcegroupby ||
                    ($hasaggregated && (empty($columnaggregation) || $columnaggregation::column_groupby()))) {
                $groupbyfields = array_merge($groupbyfields, $column->get_groupby_sql());
            }
        }

        // Rewrite collapsed aliases inside GROUP BY fragments before returning, so callers don't
        // need to know about the alias map at all.
        $groupbyfields = array_map(
            static fn(string $fragment): string => self::rewrite_fragment($fragment, $aliasmap),
            $groupbyfields,
        );

        return new self($selectfields, $groupbyfields, $aliasmap);
    }

    /**
     * Return the deduplicated SELECT fragments, in column order.
     *
     * @return string[]
     */
    public function get_select_fields(): array {
        return $this->selectfields;
    }

    /**
     * Return the GROUP BY fragments contributed by the columns, with duplicate aliases rewritten
     * to reference the canonical alias actually present in the SELECT.
     *
     * @return string[]
     */
    public function get_groupby_fields(): array {
        return $this->groupbyfields;
    }

    /**
     * Rewrite any collapsed column aliases inside the given SQL fragment so they refer to the
     * canonical alias actually present in the SELECT clause.
     *
     * Suitable for ORDER BY fragments and for any other free-form SQL that may legitimately contain
     * raw column aliases.
     */
    public function rewrite(string $fragment): string {
        return self::rewrite_fragment($fragment, $this->aliasmap);
    }

    /**
     * Rehydrate a fetched row by copying values from canonical aliases into each rewritten alias,
     * restoring the row shape that columns expect prior to formatting.
     */
    public function rehydrate(array $row): array {
        foreach ($this->aliasmap as $duplicate => $canonical) {
            if (array_key_exists($canonical, $row)) {
                $row[$duplicate] = $row[$canonical];
            }
        }

        return $row;
    }

    /**
     * @param array<string, string> $aliasmap
     */
    private static function rewrite_fragment(string $fragment, array $aliasmap): string {
        if (empty($aliasmap)) {
            return $fragment;
        }

        return (string) preg_replace_callback(
            self::ALIAS_PATTERN,
            static fn(array $matches): string => $aliasmap[$matches[0]] ?? $matches[0],
            $fragment,
        );
    }
}
