<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

declare(strict_types=1);

namespace core_reportbuilder\local\helpers;

use core_reportbuilder\local\report\column;

/**
 * Helper for deduplicating identical field SELECT expressions across report columns
 *
 * Multiple report columns frequently reference the same underlying database expression
 * (e.g. several "user fullname" columns built from the same first/last-name fields). Without
 * deduplication the report SELECT clause emits the same expression many times, which is wasteful
 * and bloats result-set size. This helper:
 *
 * 1. Collapses identical field expressions in the SELECT to a single occurrence and returns a
 *    map from each duplicate column alias to the canonical alias of the first column that
 *    contributed that SQL ({@see get_unique_fields}).
 * 2. Rewrites aliases inside ORDER BY and GROUP BY fragments so they refer to the canonical
 *    alias that actually appears in the SELECT ({@see rewrite_aliases}).
 * 3. Rehydrates a fetched row by copying canonical-alias values back into the rewritten aliases,
 *    so column formatters continue to read their own per-column aliases unchanged
 *    ({@see rehydrate_row}).
 *
 * Eligibility for deduplication is conservative:
 *
 * - Field SQL must be textually identical *after* per-column parameter renaming has been applied
 *   (which {@see column::get_fields} performs). Parameterised fields naturally diverge once
 *   parameter names are prefixed with the column index, so they fall through.
 * - The owning column must not be aggregated. Aggregation wraps the field SQL, producing distinct
 *   text that cannot collide with raw fields.
 *
 * @package     core_reportbuilder
 * @copyright   2026 Paul Holden <paulh@moodle.com>
 * @license     http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class report_fields_dedup {

    /**
     * Pattern matching a "{sql} AS {alias}" field expression where alias has the canonical
     * "c{index}_{name}" form generated by {@see column::get_fields}
     */
    private const FIELD_PATTERN = '/^(?<sql>.*) AS (?<alias>c\d+_\w+)$/s';

    /**
     * Pattern matching a single canonical column alias as a whole word
     */
    private const ALIAS_PATTERN = '/\bc\d+_\w+\b/';

    /**
     * Process the given list of columns and return both the deduplicated list of "{sql} AS {alias}"
     * SELECT fragments and a map describing which column aliases were collapsed onto which
     * canonical alias.
     *
     * Field SQL that doesn't match the canonical "{sql} AS c{index}_{name}" form (which can occur
     * for atypical aggregations) is preserved verbatim and is never deduplicated.
     *
     * @param column[] $columns Active report columns, in the order they appear in the report
     * @return array{fields: string[], aliasmap: array<string, string>} ordered SELECT fragments
     *      and a map from duplicate alias to canonical alias
     */
    public static function get_unique_fields(array $columns): array {
        $fields = [];
        $sqltoalias = [];
        $aliasmap = [];

        foreach ($columns as $column) {
            $aggregated = $column->get_aggregation() !== null;

            foreach ($column->get_fields() as $field) {
                if ($aggregated || !preg_match(self::FIELD_PATTERN, $field, $matches)) {
                    // Aggregated columns (and any non-canonical fragments) are emitted verbatim and
                    // are never collapsed against raw-field columns.
                    $fields[] = $field;
                    continue;
                }

                $sql = $matches['sql'];
                $alias = $matches['alias'];

                if (array_key_exists($sql, $sqltoalias)) {
                    // Same expression has already been emitted - record an alias rewrite, but
                    // don't add the field a second time.
                    $aliasmap[$alias] = $sqltoalias[$sql];
                } else {
                    $sqltoalias[$sql] = $alias;
                    $fields[] = $field;
                }
            }
        }

        return ['fields' => $fields, 'aliasmap' => $aliasmap];
    }

    /**
     * Rewrite any duplicate column aliases inside the given SQL fragment so they refer to the
     * canonical alias actually present in the SELECT clause.
     *
     * Suitable for ORDER BY and GROUP BY fragments produced by {@see column::get_sort_fields} and
     * {@see column::get_groupby_sql}, both of which may legitimately contain raw SQL or column
     * aliases.
     *
     * @param string $fragment
     * @param array<string, string> $aliasmap
     * @return string
     */
    public static function rewrite_aliases(string $fragment, array $aliasmap): string {
        if (empty($aliasmap)) {
            return $fragment;
        }

        return (string) preg_replace_callback(self::ALIAS_PATTERN, static function(array $matches) use ($aliasmap): string {
            return $aliasmap[$matches[0]] ?? $matches[0];
        }, $fragment);
    }

    /**
     * Rehydrate a fetched row by copying values from canonical aliases into each rewritten alias,
     * restoring the row shape that columns expect prior to formatting.
     *
     * @param array $row
     * @param array<string, string> $aliasmap
     * @return array
     */
    public static function rehydrate_row(array $row, array $aliasmap): array {
        foreach ($aliasmap as $duplicate => $canonical) {
            if (array_key_exists($canonical, $row)) {
                $row[$duplicate] = $row[$canonical];
            }
        }

        return $row;
    }
}
